<?php defined('ABSPATH')||exit;
$theme=get_option('eaiw_theme','dark');
$search=sanitize_text_field(wp_unslash($_GET['s']??'')); $event=sanitize_text_field(wp_unslash($_GET['event']??'')); $level=sanitize_key($_GET['level']??''); $page=max(1,(int)($_GET['paged']??1)); $per_page=25;
$summary=EAIW_Logger::summary(); $range=in_array((int)($_GET['range']??7),[7,30,90],true)?(int)$_GET['range']:7; $daily=EAIW_Logger::daily_summary($range); $max_daily=1; foreach($daily as $day) $max_daily=max($max_daily,(int)$day['total']);
$events=EAIW_Logger::recent(['limit'=>$per_page,'page'=>$page,'search'=>$search,'event'=>$event,'level'=>$level]); $total_events=EAIW_Logger::count(['search'=>$search,'event'=>$event,'level'=>$level]); $total_pages=max(1,(int)ceil($total_events/$per_page)); $event_names=EAIW_Logger::event_names(); $level_names=EAIW_Logger::level_names();
?>
<div class="wrap eaiw-nebula-wrap <?php echo $theme==='light'?'eaiw-light':'';?>"><div class="eaiw-nebula-bg"></div>
<div class="eaiw-topbar"><div class="eaiw-brand"><div class="eaiw-logo">≡</div><div><h1>تاریخچه فعالیت</h1><p>رویدادهای مهم اتحادیار را برای بررسی و پشتیبانی مشاهده کنید.</p></div></div><div class="eaiw-toolbar"><button type="button" id="eaiwClearActivity" class="eaiw-btn eaiw-btn-ghost">پاک‌سازی تاریخچه</button><a href="<?php echo esc_url(admin_url('admin.php?page=eaiw-nebula'));?>" class="eaiw-btn eaiw-btn-ghost">بازگشت به پیشخوان</a></div></div>
<div class="eaiw-activity-summary"><div class="eaiw-card"><span class="eaiw-summary-label">کل رویدادها</span><strong><?php echo (int)$summary['total'];?></strong></div><div class="eaiw-card"><span class="eaiw-summary-label">امروز</span><strong><?php echo (int)$summary['today'];?></strong></div><div class="eaiw-card"><span class="eaiw-summary-label">موفق</span><strong class="summary-success"><?php echo (int)$summary['levels']['success'];?></strong></div><div class="eaiw-card"><span class="eaiw-summary-label">خطا و هشدار</span><strong class="summary-warning"><?php echo (int)$summary['levels']['error']+(int)$summary['levels']['warning'];?></strong></div></div><div class="eaiw-card eaiw-activity-chart"><div class="eaiw-toolbar"><h3>روند فعالیت</h3><span class="eaiw-help">سبز: موفق · مسی: هشدار · قرمز: خطا</span></div><div class="eaiw-range-tabs"><a class="<?php echo $range===7?'is-current':'';?>" href="<?php echo esc_url(add_query_arg(['page'=>'eaiw-activity','range'=>7,'s'=>$search,'event'=>$event,'level'=>$level],admin_url('admin.php')));?>">۷ روز</a><a class="<?php echo $range===30?'is-current':'';?>" href="<?php echo esc_url(add_query_arg(['page'=>'eaiw-activity','range'=>30,'s'=>$search,'event'=>$event,'level'=>$level],admin_url('admin.php')));?>">۳۰ روز</a><a class="<?php echo $range===90?'is-current':'';?>" href="<?php echo esc_url(add_query_arg(['page'=>'eaiw-activity','range'=>90,'s'=>$search,'event'=>$event,'level'=>$level],admin_url('admin.php')));?>">۹۰ روز</a></div><div class="eaiw-bars"><?php foreach($daily as $day): $height=max(4,(int)round(($day['total']/$max_daily)*100)); $success_h=$day['total']?round(($day['success']/$day['total'])*$height):0; $warning_h=$day['total']?round(($day['warning']/$day['total'])*$height):0; $error_h=max(0,$height-$success_h-$warning_h);?><div class="eaiw-day-bar"><div class="eaiw-bar-value"><?php echo (int)$day['total'];?></div><div class="eaiw-bar" style="height:<?php echo $height;?>%"><i class="bar-success" style="height:<?php echo $success_h;?>%"></i><i class="bar-warning" style="height:<?php echo $warning_h;?>%"></i><i class="bar-error" style="height:<?php echo $error_h;?>%"></i></div><small><?php echo esc_html(wp_date('m/d',strtotime($day['date'].' UTC')));?></small></div><?php endforeach;?></div></div>
<div class="eaiw-card eaiw-top-events"><h3>پرتکرارترین فعالیت‌ها</h3><div class="eaiw-top-event-list"><?php if($summary['top_events']): foreach($summary['top_events'] as $top):?><span><b><?php echo esc_html($top['event_name']);?></b><em><?php echo (int)$top['total'];?></em></span><?php endforeach; else:?><span class="eaiw-help">هنوز فعالیتی ثبت نشده است.</span><?php endif;?></div></div>
<div class="eaiw-card"><div class="eaiw-toolbar"><h3>آخرین رویدادها</h3><span class="eaiw-help"><?php echo (int)$total_events;?> رویداد</span></div>
<form method="get" class="eaiw-activity-filter"><input type="hidden" name="page" value="eaiw-activity"><input class="eaiw-input" type="search" name="s" value="<?php echo esc_attr($search);?>" placeholder="جست‌وجو در رویدادها، شناسه یا جزئیات"><select class="eaiw-select" name="level"><option value="">همه سطح‌ها</option><?php foreach($level_names as $lk=>$ln):?><option value="<?php echo esc_attr($lk);?>" <?php selected($level,$lk);?>><?php echo esc_html($ln);?></option><?php endforeach;?></select><select class="eaiw-select" name="event"><option value="">همه رویدادها</option><?php foreach($event_names as $name):?><option value="<?php echo esc_attr($name);?>" <?php selected($event,$name);?>><?php echo esc_html($name);?></option><?php endforeach;?></select><button class="eaiw-btn eaiw-btn-primary" type="submit">جست‌وجو</button><?php if($search||$event||$level):?><a class="eaiw-btn eaiw-btn-ghost" href="<?php echo esc_url(admin_url('admin.php?page=eaiw-activity'));?>">حذف فیلتر</a><?php endif;?></form>
<?php if(!$events): ?><div class="eaiw-empty">هنوز رویدادی ثبت نشده است.</div><?php else: ?><div class="eaiw-activity-table"><table class="eaiw-table"><thead><tr><th>زمان</th><th>رویداد</th><th>شناسه پیگیری</th><th>کاربر</th><th>جزئیات</th></tr></thead><tbody><?php foreach($events as $e): ?><tr><td><?php echo esc_html($e['created_at']);?></td><td><span class="eaiw-log-level level-<?php echo esc_attr($e['level']?:'info');?>"><?php echo esc_html($level_names[$e['level']??'info']??'اطلاعات');?></span><br><strong><?php echo esc_html($e['event_name']);?></strong></td><td><code><?php echo esc_html($e['trace_id']);?></code></td><td><?php echo (int)$e['user_id']?:'سامانه';?></td><td><code><?php echo esc_html($e['context']?:'—');?></code></td></tr><?php endforeach;?></tbody></table></div><?php endif; ?></div>
<?php if($total_pages>1): ?><nav class="eaiw-pagination" aria-label="صفحه‌های تاریخچه"><?php for($i=1;$i<=$total_pages;$i++): ?><a class="<?php echo $i===$page?'is-current':'';?>" href="<?php echo esc_url(add_query_arg(['page'=>'eaiw-activity','s'=>$search,'event'=>$event,'level'=>$level,'paged'=>$i],admin_url('admin.php')));?>"><?php echo $i;?></a><?php endfor;?></nav><?php endif;?>
<script>jQuery(function($){$('#eaiwClearActivity').on('click',function(){if(!window.confirm('همه رویدادهای ثبت‌شده پاک شوند؟'))return;const b=$(this);b.prop('disabled',true).text('در حال پاک‌سازی...');$.post(EAIW.ajax,{action:'eaiw_activity_clear',_ajax_nonce:EAIW.nonce},function(r){if(r.success)location.reload();else{b.prop('disabled',false).text('پاک‌سازی تاریخچه');window.alert(r.data||'عملیات انجام نشد.');}});});});</script></div>
