<?php
defined('ABSPATH')||exit;
class EAIW_Support_Request{
 public static function create($message,$session='',$name='',$contact='',$audio_url=''){global $wpdb;$t=$wpdb->prefix.'eaiw_support_requests';$id=wp_generate_uuid4();$access=wp_generate_password(32,false,false);$wpdb->insert($t,['ticket_key'=>$id,'access_token_hash'=>hash('sha256',$access),'session_id'=>sanitize_text_field($session),'name'=>sanitize_text_field($name),'contact'=>sanitize_text_field($contact),'message'=>sanitize_textarea_field($message),'audio_url'=>esc_url_raw($audio_url),'status'=>'new']);$num=(int)$wpdb->insert_id;EAIW_Logger::log('Support request created',['ticket'=>$id],'info');self::notify($num,$id,$name,$contact,$message);return ['id'=>$num,'ticket'=>$id,'access_token'=>$access];}
 private static function notify($num,$ticket,$name,$contact,$message){$chat=trim(get_option('eaiw_telegram_order_chat',''))?:trim(get_option('eaiw_telegram_chat',''));if(!$chat||!class_exists('EAIW_Telegram'))return;EAIW_Telegram::send("درخواست جدید پشتیبانی #{$num}\nشناسه: {$ticket}\nنام: ".($name?:'ثبت نشده')."\nتماس: ".($contact?:'ثبت نشده')."\n\n".mb_substr($message,0,800), '', ['chat_id'=>$chat]);}
 public static function by_ticket($ticket,$access){global $wpdb;$t=$wpdb->prefix.'eaiw_support_requests';$row=$wpdb->get_row($wpdb->prepare("SELECT ticket_key,status,response,created_at,access_token_hash FROM $t WHERE ticket_key=%s",sanitize_text_field($ticket)),ARRAY_A);if(!$row||!hash_equals((string)$row['access_token_hash'],hash('sha256',(string)$access)))return null;return ['ticket'=>$row['ticket_key'],'status'=>$row['status'],'response'=>$row['response']?:'','created_at'=>$row['created_at']];}
 public static function update_status($id,$status,$response='',$assigned=0){global $wpdb;$allowed=['new','open','answered','closed'];if(!in_array($status,$allowed,true))return false;$t=$wpdb->prefix.'eaiw_support_requests';$old=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE id=%d",(int)$id),ARRAY_A);if(!$old)return false;$ok=(bool)$wpdb->update($t,['status'=>$status,'response'=>sanitize_textarea_field($response),'assigned_user'=>(int)$assigned?:get_current_user_id(),'priority'=>max(1,min(3,(int)($_POST['priority']??2)))],['id'=>(int)$id]);if($ok&&$response){$ht=$wpdb->prefix.'eaiw_support_history';$wpdb->insert($ht,['request_id'=>(int)$id,'user_id'=>get_current_user_id(),'response'=>sanitize_textarea_field($response)]);}if($ok&&$status==='answered'&&$response&&is_email($old['contact'])){wp_mail($old['contact'],'پاسخ درخواست پشتیبانی شما',"سلام {$old['name']}،\n\nپاسخ کارشناس به درخواست شما:\n\n{$response}\n\nشناسه پیگیری: {$old['ticket_key']}",['Content-Type: text/plain; charset=UTF-8']);}return $ok;}
 public static function update_transcript($id,$text){global $wpdb;return (bool)$wpdb->update($wpdb->prefix.'eaiw_support_requests',['transcript'=>sanitize_textarea_field($text)],['id'=>(int)$id]);}
 public static function cleanup_audio($days=7){$dir=wp_upload_dir();$base=trailingslashit($dir['basedir']);$files=glob($base.'support-request-*');$n=0;foreach($files as $f)if(is_file($f)&&filemtime($f)<time()-max(1,(int)$days)*DAY_IN_SECONDS){@unlink($f);$n++;}return $n;}
 public static function history($id){global $wpdb;$t=$wpdb->prefix.'eaiw_support_history';if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$t))!==$t)return [];return $wpdb->get_results($wpdb->prepare("SELECT * FROM $t WHERE request_id=%d ORDER BY id DESC LIMIT 10",(int)$id),ARRAY_A);}
 public static function recent($args=[]){global $wpdb;$t=$wpdb->prefix.'eaiw_support_requests';$args=wp_parse_args($args,['limit'=>50,'search'=>'','status'=>'','priority'=>0]);if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$t))!==$t)return [];$where=['1=1'];$v=[];if($args['search']!==''){$like='%'.$wpdb->esc_like(sanitize_text_field($args['search'])).'%';$where[]='(name LIKE %s OR contact LIKE %s OR message LIKE %s OR ticket_key LIKE %s)';array_push($v,$like,$like,$like,$like);}if($args['status']!==''){$where[]='status=%s';$v[]=sanitize_key($args['status']);}if((int)$args['priority']>0){$where[]='priority=%d';$v[]=(int)$args['priority'];}$v[]=max(1,min(200,(int)$args['limit']));return $wpdb->get_results($wpdb->prepare("SELECT * FROM $t WHERE ".implode(' AND ',$where)." ORDER BY id DESC LIMIT %d",$v),ARRAY_A);}
}
